<a href="https://colab.research.google.com/github/omarreess/A2ol-eh-App/blob/master/Session%204%20Assignment%20-%20NumPy%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classes

In [1]:
# Create a class that has 2 methods/functions
# first function named add and takes 2 inputs and adds them
# second function named subtract and takes 2 inputs and subtract them
# Test your function with any 2 numbers

class testC :
 
  def __init__(self,num1,num2):
    self.num1 = num1
    self.num2 = num2

  def add(self   ) : return self.num1 + self.num2

  def subtract(self ):return self.num1 - self.num2

obj1 = testC(5 , 10) 
print(f"{obj1.add()}")
print (obj1.subtract() )


15
-5


In [ ]:
# Create a class that can take variables of first and last name, create an object from the class
class testC2 : 
  def __init__(self, fName, lName):
    self.firstName = fName
    self.lastName = lName
  def f (self) :
    self .hh="sd"


obj1 = testC2("Omar","Essam")
print (obj1.firstName +" "+ obj1.lastName )


Omar Essam


# Numpy


In [ ]:
# Create a numpy array of any shape and print it
import numpy as np

arr2 = np.array([[1, 2, 3],[1,2,4]])


# Print the shape of the array 
print(arr2.shape)

# Change the first value of the array to any value and print the array
arr2[[0], [0]]=7
print (arr2)

(2, 3)
[[7 2 3]
 [1 2 4]]


In [ ]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]
              ])
# Use slicing and print
# [[7 8]
#  [11 12]]
print(a[1:3,2:4 ])

# Print [ 5  6  7  8] using indexing
print(a[1 ,: ])


# Print the 2nd column
print(a[:,1 ])


[[ 7  8]
 [11 12]]
[5 6 7 8]
[ 2  6 10]


In [ ]:
# Use boolean indexing to print even numbers only
arr = np.array(range(0,100))
print(arr[arr%2 ==0])


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [ ]:
# Convert the array to type integer, DO NOT use dtype=, check online np.astype() and use it
x = np.array([10.5, 42.123]) 

a_int = x.astype('int64')
type(a_int)


numpy.ndarray

In [ ]:
# Concatenate the 2 arrays vertically and horizontally
a = np.array([1,2,3])
b = np.array([4,5,6])

#horizontally
newhArr= np.concatenate((a,b),)
print (newhArr)

#vertically
newvArr= np.array((a,b),)
print (newvArr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Add the array V to each row of array X
x = np.array([[1,2,3], 
              [4,5,6],
              [7,8,9],
              [10, 11, 12]])
v = np.array([1, 0, 1])

#
 
newArr5 = np.empty(x.shape   , dtype=int)
newArr5=x+v

print (newArr5)  
    
 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
